apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: prometheus
  labels:
    app: node-exporter
spec:
  clusterIP: None # Headless service
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
  selector:
    app: node-exporter