apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-renderer
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-renderer
  template:
    metadata:
      labels:
        app: grafana-renderer
    spec:
      containers:
        - name: grafana-renderer
          image: grafana/grafana-image-renderer@sha256:6c432f1aed266ce56433becacd197cdab708f9089104d67664207b4fe0975055
          ports:
            - containerPort: 8081
