apiVersion: v1
kind: Service
metadata:
  name: grafana-renderer-service
  namespace: prometheus
spec:
  selector:
    app: grafana-renderer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
