{
 "title": "Podinfo Dashboard",
 "description": "Panels displaying Podinfo stats.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Podinfo Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (deployment) (\r\n  kube_deployment_spec_replicas{exported_namespace=\"podinfo\", deployment=\"podinfo\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (deployment) (\r\n  kube_deployment_status_replicas_available{exported_namespace=\"podinfo\", deployment=\"podinfo\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (deployment) (\r\n  kube_deployment_status_replicas_unavailable{exported_namespace=\"podinfo\", deployment=\"podinfo\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{exported_namespace=\"podinfo\", container=\"podinfo\"}",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Grafana up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"kubernetes-pods\", namespace=\"prometheus\", pod=~\"grafana-.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alertmanager Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"kubernetes-pods\", namespace=\"prometheus\", pod=~\"alertmanager-.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube-State-Metrics Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"kubernetes-pods\", namespace=\"prometheus\", pod=~\"kube-state-metrics-.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}