route:
  receiver: "gmail"
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 10m
  routes:
    - matchers:
      - severity="warning"
      receiver: "gmail"
    - matchers:
      - severity="critical"
      receiver: "gmail"

receivers:
  - name: "gmail"
    email_configs:
      - to: "mohamedzaahran1@gmail.com"
        from: "mohamedzaahran1@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "mohamedzaahran1@gmail.com"
        auth_identity: "mohamedzaahran1@gmail.com"
        auth_password: "WRITE_YOUR_PASSWORD_HERE"
        send_resolved: true
        require_tls: true
        tls_config:
          insecure_skip_verify: true
